name: Java CI

env:
  JDK_CURRENT: 11.0.10
  DISTRIBUTION: zulu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Build, test and deploy
        run: sbt clean test deploy
